name = "CoherentStructures"
uuid = "0c1513b4-3a13-56f1-9cd2-8312eaec88c4"
version = "0.3.6"

[deps]
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
GeometricalPredicates = "fd0ad045-b25c-564e-8f9c-8ef5c5f21267"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"
VoronoiDelaunay = "72f80fcb-8c52-57d9-aff0-40c1a3526986"

[compat]
ArnoldiMethod = "0.1, 0.2"
AxisArrays = "0.3.3, 0.4"
ColorTypes = "0.10"
DiffEqBase = "6"
Distances = "0.9, 0.10"
Ferrite = "0.3"
GeometricalPredicates = "0.3, 0.4"
Interpolations = "0.11, 0.12, 0.13"
IterativeSolvers = "0.7, 0.8, 0.9"
LinearMaps = "2, 3"
NearestNeighbors = "0.4.4"
OrdinaryDiffEq = "5.18"
ProgressMeter = "1"
RecipesBase = "0.7, 0.8, 1"
StaticArrays = "0.10, 0.11, 0.12, 1.0"
Tensors = "1.0.1"
VoronoiDelaunay = "0.4"
julia = "1.4"

[extras]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Arpack", "BenchmarkTools", "DiffEqDevTools", "Random", "Test"]
