[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
CoherentStructures = "0c1513b4-3a13-56f1-9cd2-8312eaec88c4"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StreamMacros = "1418a599-1564-4a75-98e9-b890cf8b552f"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"

[compat]
Arpack = "0.4"
Clustering = "0.13, 0.14"
Distances = "0.10"
Documenter = "0.24, 0.25, 0.26"
Interpolations = "0.13"
JLD2 = "0.1.11, 02, 0.3, 0.4"
Literate = "2.2.1"
OrdinaryDiffEq = "5.52"
Plots = "0.29, 1"
StaticArrays = "1.1"
Tensors = "1.4"
